name: 'Pull request'

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Load repository code'
        uses: 'actions/checkout@v4'
      - name: 'Setup node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 22
      - name: 'Install yarn'
        run: 'npm install -g yarn@1.22.22'
      - name: 'Install dependencies'
        run: 'yarn install'
      - name: 'Run linter'
        run: 'yarn lint'
      - name: 'Build'
        run: 'yarn build'
